version: "3.9"

services:
  back:
    build: ./back

    container_name: back
    restart: always

    environment:
      DATABASE_URL: ${DATABASE_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}

    ports:
      - ${BACKEND_PORT}:3000

    volumes:
      - ./back/src:/app/src
      - ./back/prisma:/app/prisma
      - ./back/package.json:/app/package.json

    depends_on:
      - database

  test:
    build: ./back

    container_name: test
    entrypoint: /app/test-entrypoint.sh

    environment:
      DATABASE_URL: ${TEST_DATABASE_URL}

    volumes:
      - ./back/src:/app/src
      - ./back/prisma:/app/prisma
      - ./back/__tests__:/app/__tests__
      - ./back/package.json:/app/package.json

    depends_on:
      - database

  adminer:
    image: adminer
    container_name: adminer

    restart: always

    environment:
      ADMINER_DESIGN: ${ADMINER_DESIGN}

    ports:
      - ${ADMINER_PORT}:8080

    links:
      - database:db

  database:
    image: postgres:16-alpine
    container_name: database

    restart: always

    environment:
      POSTGRES_DB: count_of_money
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
