name: Backend tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Backend tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set environment variables
      run: cp .env.local .env

    - name: Start tests
      run: docker compose up test
